services:
  postgres:
    image: supabase/postgres:15.1.0.151
    container_name: chunking-expt-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
    volumes:
      # Named volume for data persistence
      - postgres_data:/var/lib/postgresql/data
      # Initialization scripts
      - ./postgres/init:/docker-entrypoint-initdb.d
      # Custom PostgreSQL configuration (IPv4 only)
      - ./postgres/postgresql.conf:/etc/postgresql/postgresql.conf:ro
      - ./postgres/pg_hba.conf:/etc/postgresql/pg_hba.conf:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h 127.0.0.1 -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    command:
      - postgres
      - -c
      - config_file=/etc/postgresql/postgresql.conf
      - -c
      - hba_file=/etc/postgresql/pg_hba.conf
      - -c
      - listen_addresses=0.0.0.0
    env_file:
      - ../../.env

volumes:
  postgres_data:
    name: chunking-expt-postgres-data